name: ddp
description: MeteorJS DDP library for Dart.
version: 0.0.13
author: haoguo <bard.guo@gmail.com>
homepage: https://github.com/haoguo/ddp
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  tuple: ^2.0.0

dev_dependencies:
  test: ^1.20.1